name: ci

on: [push]


jobs:
  artifacts:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: jvansanten/poetry-export-to-legacy-action@master
    - run: git status
